sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
before_install:
  - export TZ='Asia/Shanghai'
branches:
  only:
    - develop # build develop branch only
install:
  - npm install
script:
  - hexo clean
  - hexo generate # generate static files
after_script:
  - git clone https://${GH_REP} .deploy_git
  - cd .deploy_git
  - git checkout master
  - cd ../
  - mv .deploy_git/.git/ ./public/
  - cd ./public
  - git config user.name "WangHailin"
  - git config user.email "whlsoulmate@gmail.com"
  - git add .
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
  - git push --force --quiet "https://$GH_TOKEN@${GH_REP}" master:master
env:
  global:
    - GH_REP: github.com/WsWHL/wswhl.github.io.git
notifications:
  email:
    recipients:
      - whlsoulmate@gmail.com
    on_success: change # default: change
    on_failure: always # default: always
